### ISSUE TITLE
User `arn:aws:sts::XXXXXXXXX:assumed-role/sam-batch-test-SendEmailFunctionRole-XXXXXX/sam-batch-test-SendEmailFunction-1FHgDhZRZNoE' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:us-west-1:XXXXXXXX:identity/my@customdomain.com'

### ISSUE THREAD

**Issue by supermikol** [aws-samples/aws-serverless-batch-architecture#1]
I just ran the template as-is with an existing domain (that is registered and verified) and ran into a SES permissions issue.
```
User `arn:aws:sts::XXXXXXXXX:assumed-role/sam-batch-test-SendEmailFunctionRole-XXXXXX/sam-batch-test-SendEmailFunction-1FHgDhZRZNoE' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:us-west-1:XXXXXXXX:identity/my@customdomain.com'
```
I managed to get around the issue by appending permissions specific to the sender email, but I'm not sure if this is the best practice solution. Furthermore, it doesn't seem like providing permission for the SESIdentityName is necessary.
```
        - SESCrudPolicy:
            IdentityName: !Ref SESIdentityName
        - SESCrudPolicy: # This is what I added to resolve the issue
            IdentityName: !Ref SESSender # This is what I added to resolve the issue
```
